# Cart Management Service - Medium (transactional)
image:
  repository: santhe/cart-management-service
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: cart-management-service
fullnameOverride: cart-management-service

service:
  port: 8000

resources:
  requests:
    cpu: 100m
    memory: 96Mi
  limits:
    cpu: 300m
    memory: 192Mi

istio:
  enabled: true
  virtualService:
    enabled: true
    hosts:
      - cart-management-service.local
    routes:
      - destination:
          host: cart-management-service
          port:
            number: 8000

migrations:
  enabled: true

env:
  - name: DATABASE_URL
    value: "postgresql+psycopg://postgres:postgres@postgres-postgresql.database.svc.cluster.local:5432/cart_management_service_db"
  - name: SECRET_KEY
    value: "supersecret"
