# Notification Service - Medium (external API calls)
image:
  repository: santhe/notification-service
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: notification-service
fullnameOverride: notification-service

service:
  port: 8000

resources:
  requests:
    cpu: 100m
    memory: 96Mi
  limits:
    cpu: 300m
    memory: 192Mi

istio:
  enabled: true
  virtualService:
    enabled: true
    hosts:
      - notification-service.local
    routes:
      - destination:
          host: notification-service
          port:
            number: 8000

migrations:
  enabled: true
