{{- if .Values.istio.enabled }}
{{- if .Values.istio.destinationRule.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "microservice.fullname" . }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
spec:
  host: {{ include "microservice.fullname" . }}
  subsets:
    {{- toYaml .Values.istio.destinationRule.subsets | nindent 4 }}
{{- end }}
{{- end }}
