{{- if .Values.istio.enabled }}
{{- if .Values.istio.virtualService.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "microservice.fullname" . }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
spec:
  gateways:
    {{- toYaml .Values.istio.virtualService.gateways | nindent 4 }}
  hosts:
    {{- toYaml .Values.istio.virtualService.hosts | nindent 4 }}
  http:
    - route:
      {{- if .Values.istio.virtualService.routes }}
      {{- toYaml .Values.istio.virtualService.routes | nindent 6 }}
      {{- else }}
      - destination:
          host: {{ include "microservice.fullname" . }}
      {{- end }}
{{- end }}
{{- end }}
